const en = {
  featureSelection: "Feature Selection",
  correlationAnalysis: "Correlation Analysis",
  applySelection: "Apply Selection",
  clearAll: "Clear All",
  colorLegend: "Color Legend",
  updateMap: "Update Map & Calculate Correlation",
  correlationResults: "Correlation Results",
  featureCorrelationMatrix: "Feature Correlation Matrix",
  gbGender: "Gender Features (Cyan)",
  gbClassifier: "Classifier Features (Orange)",
  value1Cyan: "Value = 1 (Cyan)",
  value0Blue: "Value = 0 (Light Blue)",
  naGray: "NA (Gray Border)",
  value1Orange: "Value = 1 (Orange)",
  value0Orange: "Value = 0 (Light Orange)",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  selectedHint: "Selected ",
  chatTitle: "AI Assistant",
  send: "Send",
  suggestions: [
    "What are the most important gender features?",
    "Recommend features for social analysis",
    "Show correlations between feature groups",
    "Analyze geographical distribution",
    "Propose a research question",
    "Suggest analysis approaches"
  ],
  apiKeyTitle: "Set Gemini API Key",
  apiKey: "API Key",
  apiKeyPlaceholder: "Please enter your Gemini API Key",
  apiKeyNote1: "• API Key is only saved in your local browser, not uploaded to server",
  apiKeyNote2: "• You can get a free API Key at ",
  apiKeyNote3: "• After setting, you can use the AI assistant feature",
  apiKeySave: "Save",
  apiKeyCancel: "Cancel",
  apiKeyDesc: "Instructions",
  apiKeyGet: "Google AI Studio",
  eaSocial: "EA Features (Social)",
  eaEcological: "EA Features (Ecological)",
  treeTitle: "Phylogenetic Tree Visualization",
  loadTree: "Load Tree",
  selectTree: "Select a tree file...",
  mapTitle: "Language Map",
  welcome: "Hello! I'm your AI language analysis assistant. I can help you analyze linguistic features, recommend analysis approaches, and provide insights about your dataset. Ask me anything about the language data!",
  langToggle: "中文/English",
  // 新增的翻译
  gbFeatureType: "Grambank (GB) Feature",
  eaFeatureType: "D-PLACE (EA) Feature",
  ecologicalFeatureType: "Environmental/Biodiversity Feature",
  otherFeatureType: "Other Feature",
  featureInfoTitle: "Feature Information",
  close: "Close",
  noDescription: "No description available for this feature.",
  featureType: "Feature Type",
  // Linguistic Knowledge Base
  knowledgeBaseTitle: "📚 Linguistic Knowledge Base",
  knowledgeBaseDesc: "Click on any concept to get AI explanation and connections to your data:",
  // Knowledge Base Categories
  all: "All",
  typology: "Typology",
  universals: "Universals",
  areal: "Areal",
  methods: "Methods",
  // Analysis Method Categories
  correlation: "Correlation",
  phylogenetic: "Phylogenetic",
  spatial: "Spatial",
  sociolinguistics: "Sociolinguistics",
  ecolinguistics: "Ecolinguistics",
  historical: "Historical",
  // Complexity
  low: "Low",
  medium: "Medium",
  high: "High",
  // Common Text
  selected: "Selected",
  checkAI: "Check the AI Assistant for detailed explanation and connections to your data.",
  examples: "Examples",
  keyTheories: "Key Theories",
  relevance: "Relevance",
  useCase: "Use Case",
  category: "Category",
  complexity: "Complexity",
  aiExplanation: "AI Explanation"
};
export default en; 