const zh = {
  featureSelection: "特征选择",
  correlationAnalysis: "相关性分析",
  applySelection: "应用选择",
  clearAll: "全部清除",
  colorLegend: "颜色图例",
  updateMap: "更新地图并计算相关性",
  correlationResults: "相关性结果",
  featureCorrelationMatrix: "特征相关性矩阵",
  gbGender: "性别特征（青色）",
  gbClassifier: "分类词特征（橙色）",
  value1Cyan: "值=1（青色）",
  value0Blue: "值=0（浅蓝）",
  naGray: "NA（灰边）",
  value1Orange: "值=1（橙色）",
  value0Orange: "值=0（浅橙）",
  selectAll: "全选",
  deselectAll: "全不选",
  selectedHint: "已选",
  chatTitle: "AI助手",
  send: "发送",
  suggestions: [
    "最重要的性别特征有哪些？",
    "推荐社会分析特征",
    "展示特征组相关性",
    "分析地理分布",
    "提出研究问题",
    "建议分析方法"
  ],
  apiKeyTitle: "设置 Gemini API Key",
  apiKey: "API密钥",
  apiKeyPlaceholder: "请输入你的Gemini API Key",
  apiKeyNote1: "• API Key只保存在本地浏览器，不会上传到服务器",
  apiKeyNote2: "• 你可以在 ",
  apiKeyNote3: "• 设置后即可使用AI助手功能",
  apiKeySave: "保存",
  apiKeyCancel: "取消",
  apiKeyDesc: "说明",
  apiKeyGet: "Google AI Studio",
  eaSocial: "EA特征（社会）",
  eaEcological: "EA特征（生态）",
  treeTitle: "系统发育树可视化",
  loadTree: "加载树",
  selectTree: "请选择树文件...",
  mapTitle: "语言地图",
  welcome: "你好！我是你的AI语言分析助手。我可以帮助你分析语言特征、推荐分析方法，并为你的数据集提供见解。欢迎随时提问！",
  langToggle: "中文/English",
  // 新增的翻译
  gbFeatureType: "Grambank (GB) 特征",
  eaFeatureType: "D-PLACE (EA) 特征",
  ecologicalFeatureType: "环境/生物多样性特征",
  otherFeatureType: "其他特征",
  featureInfoTitle: "特征信息",
  close: "关闭",
  noDescription: "此特征暂无描述。",
  featureType: "特征类型",
  // 语言学知识库和分析方法
  knowledgeBaseTitle: "📚 语言学知识库",
  methodSuggestionTitle: "📊 语言学分析方法",
  knowledgeBaseDesc: "点击任何概念获取AI解释和与当前数据的关联：",
  methodSuggestionDesc: "点击任何方法获取AI解释和实施建议：",
  // 知识库分类
  all: "全部",
  typology: "类型学",
  universals: "普遍性",
  areal: "区域",
  methods: "方法",
  // 分析方法分类
  correlation: "相关性",
  phylogenetic: "系统发育",
  spatial: "空间",
  sociolinguistics: "社会语言学",
  ecolinguistics: "生态语言学",
  historical: "历史",
  // 复杂度
  low: "简单",
  medium: "中等",
  high: "复杂",
  // 通用文本
  selected: "已选择",
  checkAI: "查看AI助手获取详细解释和与数据的关联。",
  examples: "例子",
  keyTheories: "主要理论",
  relevance: "相关性",
  useCase: "用途",
  category: "分类",
  complexity: "复杂度"
};
export default zh; 