const zh = {
  featureSelection: "特征选择",
  correlationAnalysis: "相关性分析",
  applySelection: "应用选择",
  clearAll: "全部清除",
  colorLegend: "颜色图例",
  updateMap: "更新地图并计算相关性",
  correlationResults: "相关性结果",
  featureCorrelationMatrix: "特征相关性矩阵",
  gbGender: "性别特征（青色）",
  gbClassifier: "分类词特征（橙色）",
  value1Cyan: "值=1（青色）",
  value0Blue: "值=0（浅蓝）",
  naGray: "NA（灰边）",
  value1Orange: "值=1（橙色）",
  value0Orange: "值=0（浅橙）",
  selectAll: "全选",
  deselectAll: "全不选",
  selectedHint: "已选",
  chatTitle: "AI助手",
  send: "发送",
  suggestions: [
    "最重要的性别特征有哪些？",
    "推荐社会分析特征",
    "展示特征组相关性",
    "分析地理分布",
    "提出研究问题",
    "建议分析方法"
  ],
  apiKeyTitle: "设置 Gemini API Key",
  apiKey: "API密钥",
  apiKeyPlaceholder: "请输入你的Gemini API Key",
  apiKeyNote1: "• API Key只保存在本地浏览器，不会上传到服务器",
  apiKeyNote2: "• 你可以在 ",
  apiKeyNote3: "• 设置后即可使用AI助手功能",
  apiKeySave: "保存",
  apiKeyCancel: "取消",
  apiKeyDesc: "说明",
  apiKeyGet: "Google AI Studio",
  eaSocial: "D-PLACE特征（社会）",
  eaEcological: "D-PLACE特征（生态）",
  treeTitle: "系统发育树可视化",
  loadTree: "加载树",
  selectTree: "请选择树文件...",
  mapTitle: "语言地图",
  welcome: "你好！我是你的AI语言分析助手。我可以帮助你分析语言特征、推荐分析方法，并为你的数据集提供见解。欢迎随时提问！",
  langToggle: "中文/English",
  // 新增的翻译
  gbFeatureType: "Grambank (GB) 特征",
  eaFeatureType: "D-PLACE 特征",
  dplaceFeatureType: "D-PLACE 特征",
  ecologicalFeatureType: "环境/生物多样性特征",
  otherFeatureType: "其他特征",
  featureInfoTitle: "特征信息",
  close: "关闭",
  noDescription: "此特征暂无描述。",
  featureType: "特征类型",
  // 语言学知识库
  knowledgeBaseTitle: "📚 语言学知识库",
  knowledgeBaseDesc: "点击任何概念获取AI解释和与当前数据的关联：",
  // 知识库分类
  all: "全部",
  typology: "类型学",
  universals: "普遍性",
  areal: "区域",
  methods: "方法",
  // 分析方法分类
  correlation: "相关性",
  phylogenetic: "系统发育",
  spatial: "空间",
  sociolinguistics: "社会语言学",
  ecolinguistics: "生态语言学",
  historical: "历史",
  // 复杂度
  low: "简单",
  medium: "中等",
  high: "复杂",
  // 通用文本
  selected: "已选择",
  checkAI: "查看AI助手获取详细解释和与数据的关联。",
  examples: "例子",
  keyTheories: "主要理论",
  relevance: "相关性",
  useCase: "用途",
  category: "分类",
  complexity: "复杂度",
  aiExplanation: "AI解释",
  // 分组分析相关
  selectGroupsToAnalyze: "选择要分析的{type}:",
  languageFamily: "语系",
  region: "地区",
  macroarea: "大区域",
  selectedCount: "已选择: {count}",
  // 相关性分析相关
  correlationMethodPearson: "皮尔逊相关系数",
  correlationMethodSpearman: "斯皮尔曼等级相关系数",
  correlationMethodKendall: "肯德尔等级相关系数",
  groupAnalysisType: "分组分析类型",
  groupAnalysisNone: "不分组（整体分析）",
  groupAnalysisByFamily: "按语系分组",
  groupAnalysisByRegion: "按地区分组",
  groupAnalysisByMacroarea: "按大区域分组",
  groupCorrelationTitle: "组间相关性 ({method})",
  groupCorrelationTitleFallback: "组间相关性",
  groupCorrelationSampleSize: "样本量: {size} 语言",
  groupedCorrelationTitle: "分组相关性分析",
  groupedCorrelationByType: "按{type}分组",
  groupOverviewTitle: "分组概览",
  sampleSize: "样本量",
  sampleSizeTooSmall: "样本量太小",
  languages: "语言",
  correlationMatrixTitle: "相关性矩阵",
  vs: "vs",
  pValue: "p值",
  groupDifferencesTitle: "分组间相关性差异分析",
  compareCorrelationPatterns: "比较不同{type}间的相关性模式差异",
  cannotCalculateDifferences: "无法计算差异（需要至少2个有效分组）",
  maxDifferencesTitle: "最大差异特征对",
  featurePair: "特征对",
  maxDifference: "最大差异",
  groupsWithMaxDiff: "差异最大的分组",
  featureCorrelationTitle: "特征相关性",
  featureCorrelationSampleSize: "样本量: {size} 语言",
  clickToGetAIExplanation: "点击获取AI解释",
  calculating: "计算中...",
  calculateCorrelations: "计算相关性",
  // 动态特征选择器相关
  dynamicFeatureSelectorTitle: "动态特征选择",
  clearAllFeatures: "清除所有",
  selectAllGbFeatures: "全选GB",
  selectAllEaFeatures: "全选D-PLACE",
  selectedFeaturesCount: "已选择",
  gbFeatures: "个GB特征",
  eaFeatures: "个D-PLACE特征",
  hideSelector: "隐藏",
  showSelector: "显示",
  searchGbPlaceholder: "搜索GB特征...",
  searchEaPlaceholder: "搜索EA特征...",
  loadingData: "加载中...",
  applyFeatures: "应用选择",
  selectAtLeastOneFeature: "请先选择至少一个特征",
  noDataToDownload: "没有可下载的数据，请先应用特征选择",
  downloadDataError: "下载数据时出错，请检查控制台",
  downloadFormatError: "下载{format}格式数据时出错，请检查控制台",
  loadFamilyMappingError: "加载语系映射失败",
  // 数据模式切换相关
  dataModeTitle: "数据模式",
  staticDataLabel: "静态数据 (预处理的CSV)",
  dynamicDataLabel: "动态数据 (实时查询数据库)",
  currentDataPoints: "当前数据点: {count} 个语言",
  reloadData: "重新加载数据",
  downloadStaticData: "下载静态数据",
  unavailableDownload: "不可下载",
  chooseDownloadFormat: "选择下载格式",
  csvFormat: "CSV",
  tsvFormat: "TSV",
  jsonFormat: "JSON",
  summaryFormat: "摘要",
  csvFormatDescription: "CSV格式，兼容Excel",
  tsvFormatDescription: "TSV格式，Excel友好",
  jsonFormatDescription: "JSON格式，便于程序处理",
  summaryFormatDescription: "数据摘要报告",
  loadingDataMessage: "⏳ 正在处理数据...",
  downloadSuccess: "成功下载 {count} 行静态数据",
  // 智能特征推荐相关
  smartFeatureRecommendationsTitle: "🎯 智能特征推荐",
  aiSmartRecommendations: "AI智能推荐",
  enterResearchQuestionOrKeywords: "输入研究问题或关键词...",
  generateRecommendations: "生成推荐",
  currentSelection: "当前选择",
  successfullyAddedFeatures: "成功添加了 {count} 个新特征到选择中！",
  databaseOverviewTitle: "数据库概览",
  grammarFeatures: "个语法特征",
  socialCulturalFeatures: "个社会文化特征",
  total: "总计",
  features: "个特征",
  researchIdeasTitle: "🔬 研究建议",
  exploreThisIdea: "探索这个想法",
  discoveredFeaturesTitle: "🔍 从数据库中发现的特征",
  getAIExplanation: "获取AI解释",
  // 地图弹窗相关
  languageId: "语言ID",
  none: "无",
  sizeValue: "大小值",
  na: "N/A",
  clickToSeeDetails: "点击查看详情",
  doubleClickToGetAIExplanation: "双击获取AI解释",
  recommendedFeaturesTitle: "🔍 推荐特征",
  hide: "隐藏",
  browse: "浏览",
  showingRecommendedFeatures: "显示{count}个推荐特征",
  generateRecommendationsError: "生成推荐失败"
};
export default zh; 